services:
  postgres:
    image: postgres:16-alpine
    container_name: futebol-db
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: futebol_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
